### ISSUE TITLE
Static website?

### ISSUE THREAD

**Issue by rraallvv** [kodaxx/spark-payments-dash#1]
Just a simple question. Can `spark-payments-dash` work as a static website, like for instance those hosted at github.io? Keep up the good work.

**Comment by kodaxx** [comment]
Yes, in fact get-spark.com is hosted on GitHub (though it is the
spark-dash-webpack repo, because it is the most up to date)

**Comment by rraallvv** [comment]
@kodaxx Awesome! Thank you for your prompt reply.
